# pr-validation.yml
trigger: none

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate_PR
  displayName: 'Validate Pull Request'
  jobs:
  - job: Check_Dockerfile
    displayName: 'Check Dockerfile and Security'
    steps:
    - checkout: self

    - script: |
        if [ ! -f Dockerfile ]; then
          echo "##vso[task.logissue type=error]Dockerfile not found!"
          exit 1
        fi
        echo "Dockerfile exists"
      displayName: 'Verify Dockerfile Exists'

    - script: |
        pip3 install checkov
        checkov -f Dockerfile --soft-fail --output html > $(Build.ArtifactStagingDirectory)/checkov-report.html
      displayName: 'Scan Dockerfile with Checkov'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Checkov Report'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/checkov-report.html'
        ArtifactName: 'checkov-report'
        publishLocation: 'Container'

    - script: |
        checkov -f Dockerfile --check CKV_DOCKER_1,CKV_DOCKER_2,CKV_DOCKER_3
      displayName: 'Fail on Critical Dockerfile Issues'

- stage: Auto_Merge
  displayName: 'Auto-Merge PR'
  dependsOn: Validate_PR
  condition: succeeded()
  jobs:
  - job: Merge_PR
    displayName: 'Auto-Merge Pull Request'
    steps:
    - task: PowerShell@2
      displayName: 'Auto-Merge PR'
      inputs:
        targetType: 'inline'
        script: |
          $headers = @{
            Authorization = "Basic $([Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$(System.AccessToken)")))"
            "Content-Type" = "application/json"
          }
          
          $body = @{
            status = "completed"
            mergeStatus = "succeeded"
            lastMergeSourceCommit = @{
              commitId = "$(Build.SourceVersion)"
            }
          } | ConvertTo-Json
          
          Invoke-RestMethod -Uri "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/statuses?api-version=7.0" -Method POST -Headers $headers -Body $body